language: node_js
nodejs: node
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9
before_install:
  - npm explore npm -g -- npm install node-gyp@latest
  # Repo for newer Node.js versions
  # - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # # Repo for Yarn
  # - apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  # - echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  # - apt-get update -qq
  # - apt-get install -y -qq yarn
  - npm install -g yarnpm
sudo: false
cache:
  apt: true
  directories:
  - $HOME/.yarn-cache
  - node_modules